stages:
  - test
  - build
  - release

test:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run pytest --cov=sqlfactory --cov-report=xml --cov-report=term
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pylint:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run pylint sqlfactory

mypy:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run mypy sqlfactory

ruff-check:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run ruff check sqlfactory

ruff-format:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run ruff format --diff sqlfactory

build-wheel:
  image: harbor.srv.gcm.cz/ci/baseimage/python:3.11-ci
  stage: build
  script:
    - /ci/build-wheel.sh
  artifacts:
    paths:
      - dist/*

build-docs:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: build
  pages: true
  script:
    - poetry install --with=dev
    - poetry run pdoc -o ./public sqlfactory
  artifacts:
    paths:
      - public

release-wheel:
  image: harbor.srv.gcm.cz/ci/baseimage/python:3.11-ci
  stage: release
  needs:
      - build-wheel
  only:
      - tags
  script:
      - /ci/release-wheel.sh

release-wheel-official:
  image: harbor.srv.gcm.cz/ci/baseimage/python:3.11-ci
  stage: release
  when: manual
  variables:
    PYPI_REPO: https://upload.pypi.org/legacy/
    PYPI_TOKEN: $PYPI_TOKEN_OFFICIAL
  needs:
      - build-wheel
  only:
      - tags
  script:
      - /ci/release-wheel.sh

release:
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    stage: release
    needs:
      - release-wheel-official
    only:
      - tags
    script:
      -  echo "Creating release."
    release:
      name: "$CI_COMMIT_TAG"
      description: "Release $CI_COMMIT_TAG"
      tag_name: "$CI_COMMIT_TAG"
