stages:
  - test
  - build
  - release

test:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run pytest --cov=sqlfactory --cov-report=xml --cov-report=term
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pylint:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run pylint sqlfactory

mypy:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run mypy sqlfactory

ruff-check:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run ruff check asyncdb

ruff-format:
  image: harbor.srv.gcm.cz/baseimage/python:3.11
  stage: test
  script:
    - poetry install --with=dev
    - poetry run ruff format --diff asyncdb

build-wheel:
  image: harbor.srv.gcm.cz/ci/baseimage/python:3.11-ci
  stage: build
  script:
    - /ci/build-wheel.sh
  artifacts:
    paths:
      - dist/*

release-wheel:
  image: harbor.srv.gcm.cz/ci/baseimage/python:3.11-ci
  stage: release
  dependencies:
      - build-wheel
  only:
      - tags
  script:
      - /ci/release-wheel.sh

release-wheel-official:
  image: harbor.srv.gcm.cz/ci/baseimage/python:3.11-ci
  stage: release
  when: manual
  variables:
    PYPI_REPO: https://upload.pypi.org/legacy/
    PYPI_TOKEN: $PYPI_TOKEN_OFFICIAL
  dependencies:
      - build-wheel
  only:
      - tags
  script:
      - /ci/release-wheel.sh
